config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'home#top'
  #get '/articles/:id' => 'articles#show', as: 'article'

  #get '/articles/:id/edit' => 'articles#edit', as: 'edit_article'
  #patch '/articles/:id' => 'article#update', as: 'update_article'
#get '/articles' => 'articles#index'

#	end

resources :articles 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
	def index
	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :setarticle, only: [:show, :edit, :update, :destroy]
	
	def index
		@articles = Article.all
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		@article.save
		redirect_to '/articles'
	end

	def show
		@article = Article.find(params[:id])
	end

	def edit
   		@article = Article.find(params[:id])
  	end

  	def update
  		@article = Article.find(params[:id])
    	@article.update(article_params)
    	redirect_to article_path
  	end

  	def destroy
		@article = Article.find(params[:id])
    	@article.destroy
    	redirect_to articles_path
  	end

	private

	def setarticle
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(
								:title,
								:body,
								:author
								)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def top
 	
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/article/index.html.erb
<h1>投稿一覧</h1>

app/views/articles/edit.html.erb
 <h1>編集</h1>

<%= form_for(@article) do |f| %>
 
 <div>タイトル:<%= f.text_field :title %></div>
 <div>本文:<%= f.text_area :body %></div>
 <div>著者:<%= f.text_field :author %></div>

 <div><%= f.submit "編集" %></div>


<% end %>

app/views/articles/index.html.erb
<h1 class="index-name">投稿一覧</h1>
<% @articles.each do |article| %>
  <h2 class="articles-title"><%= link_to article.title, article_path(article.id) %></h2>

<%= link_to "削除", article_path(article.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>

<% end %>

app/views/articles/new.html.erb
 <h1>新規投稿</h1>

<%= form_for(@article) do |f| %>
 
 <div>タイトル:<%= f.text_field :title %></div>
 <div>本文:<%= f.text_area :body %></div>
 <div>著者:<%= f.text_field :author %></div>

 <div><%= f.submit "送信" %></div>


<% end %>

app/views/articles/show.html.erb
<h1 class="article-title">投稿詳細</h1>

<h2 class="article">タイトル</h2>
<div class="article-link"><%= @article.title %></div>
<h2 class="article">本文</h2>
<div class="article-link"><%= @article.body %></div>
<h2 class="article">著者</h2>
<div class="article-link"><%= @article.author %></div>


<div class="edit-button"><%= link_to "編集する", edit_article_path(@article.id), class: "btn edit-btn" %></div>
<div class="delete-button"><%= link_to "削除", article_path(@article.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></div>

app/views/home/top.html.erb
<%= image_tag('profile.jpg', :class => "image-tag-class") %>

<h1 class="top-name">Nana Shimizu</h1>

<div class="back-img">
	<h1>トップページ</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShimizuDiary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if user_signed_in? %>
  		Logged in as <%= current_user.email %>
  		<% link_to "ログアウト", destroy_user_session_path, method: :delete %>
  		<%= link_to 'プロフィール変更', edit_user_registration_path %>
  	<% else %>
  		<%= link_to "新規登録", new_user_registration_path %>
  		<%= link_to "ログイン", new_user_session_path %>
  	<% end %>
    <%= yield %>
  </body>
</html>